### Get products
GET http://localhost:5001/api/products
Accept: application/json

###

### Create new product
POST http://localhost:5001/api/products
Content-Type: application/json

{
    "name": "Shorts Omega",
    "category": "Shorts",
    "quantity": 10,
    "price": 500,
    "description": "Shorts description"
}

### Get product by id
GET http://localhost:5001/api/products/689c973d0c4fb8d3f7b98cf2

### Delete product by id
DELETE http://localhost:5001/api/products/689c973d0c4fb8d3f7b98cf2